version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - /etc/loki:/etc/loki
    command:
      - "--config.file=/etc/loki/loki.yml"
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /etc/promtail:/etc/promtail
    command:
      - "--config.file=/etc/promtail/promtail.yml"
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
